### ISSUE TITLE
release pengines on pypi

### ISSUE THREAD

**Issue by cmungall** [ian-andrich/PythonPengines#1]
It's pretty straightforward, happy to help

May want to coordinate with @eugeneai who also has a python pengines repo

**Comment by ian-andrich** [comment]
Cool, I had no idea anyone else was working on a PythonPengines API.  I'll get on it this weekend.

**Comment by cmungall** [comment]
Just a friendly ping to see if there was still interest in doing this

**Comment by eugeneai** [comment]
Hi!
If You like, You can release PythonEngines at PyPi.

Best regards,
Evgeny

**Comment by ian-andrich** [comment]
Should be released on pypi.  Please let me know if anything else happens, otherwise I'm closing this as resolved.
