### ISSUE TITLE
Application keyword in PengineBuilder has no effect

### ISSUE THREAD

**Issue by peterkamatej** [ian-andrich/PythonPengines#12]
The reason is that in the getRequestBodyCreate() method, the following is missing:
`if self.application is not None:
    data["application"] = self.application`

I have made a commit which fixes this issue, but it seems I have no rights to push a new branch and create a pull request.

**Comment by ian-andrich** [comment]
I'm new to hosting public repositories, is there anything that I need to do so you can make a pull request?

**Comment by peterkamatej** [comment]
I´m new also to contributing to public repositories :-). Maybe you could add me as a contributor somehow?

**Comment by cmungall** [comment]
Anyone should be able to make a PR. Matej, did you remember to fork first?

(or if it small just paste the results of git diff here...)

**Comment by peterkamatej** [comment]
I did the fork, but later, and then forgot to push to my fork instead of the main one :-)
Now it's ready I think

**Comment by ian-andrich** [comment]
Closed by merging in pull request.  Congratulations again!
