### ISSUE TITLE
Enable travis

### ISSUE THREAD

**Issue by cmungall** [ian-andrich/PythonPengines#17]
@ian-andrich would you be able to enable travis-ci here: https://travis-ci.org/ian-andrich/PythonPengines

That way we can have checks running on PRs.

Thanks!!

**Comment by ian-andrich** [comment]
Ok, just signed up, let me figure out what else needs to be done.

**Comment by ian-andrich** [comment]
@cmungall Notes from TravisCI website

> Python builds are not available on the macOS environment.

Does this negatively affect you?
Going to set it up to run on windows and linux in short term.
I will start a travis ci branch and at least get the skeleton up.

**Comment by ian-andrich** [comment]
Ok -- windows doesn't work either.

**Comment by ian-andrich** [comment]
@cmungall Ok, got it working.

**Comment by cmungall** [comment]
Just to be clear I am mostly interested in travis for unit tests, not for
making builds for people to use - I hadn't considered the latter. Could be
v useful - but maybe much harder than just getting tests working on PRs!

**Comment by ian-andrich** [comment]
Same. I've run into cross os issues relating to lower level functionality like time and networking before.

I hadn't there doesn't appear to be much we need to build at present.
